spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=Ev_Charging_DB
server.port=8080
server.servlet.session.timeout=30m
spring.data.mongodb.uri=mongodb://localhost:27017/EV_Charging_DB
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.datasource.username=admin
spring.datasource.password=password
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=priyankashinde102099@gmail.com
spring.mail.password=fzho bmce ckjo vgjs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.main.allow-bean-definition-overriding=true
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG


